# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 18:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('Person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('abc', models.CharField(help_text='Inform your last name', max_length=50, verbose_name='ultimo nome')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.Person',),
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('Person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fgh', models.CharField(help_text='Inform your last name', max_length=50, verbose_name='ultimo nome')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.Person',),
        ),
    ]
