# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='cep',
            field=models.CharField(default='', max_length=8, verbose_name='CEP'),
        ),
    ]
