# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='comment_receptionist',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Comentário do receptionista'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age_range',
            field=models.IntegerField(choices=[(0, 'Faixa etária indefinida'), (1, '0 até 28 dias'), (2, '29 dias à 2 meses'), (3, '2 meses à 3 anos'), (4, '3 anos à 10 anos'), (5, 'Acima de 10 anos')], default=0, verbose_name='Faixa etária'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='classification',
            field=models.IntegerField(choices=[(0, 'Não classificado'), (1, 'Atendimento Imediato'), (2, 'Atendimento Hospitalar'), (3, 'Atendimento Ambulatorial'), (4, 'Atendimento Eletivo')], default=0, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Sexo indefinido'), (1, 'Feminino'), (2, 'Masculino')], default=0, verbose_name='Genero'),
        ),
    ]
