# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='block',
            field=models.CharField(max_length=50, verbose_name='Quadra'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='neighborhood',
            field=models.CharField(max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='attendant',
            name='block',
            field=models.CharField(max_length=50, verbose_name='Quadra'),
        ),
        migrations.AlterField(
            model_name='attendant',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='attendant',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='attendant',
            name='neighborhood',
            field=models.CharField(max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='attendant',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='attendant',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Rua'),
        ),
    ]
