# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='number',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Numero'),
        ),
    ]
