# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(help_text='Informe a data de Nascimento', null=True, verbose_name='Data de Nascimento'),
        ),
    ]
