# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Staff')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.staff', models.Model),
        ),
    ]
