# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profile',
            field=models.IntegerField(choices=[('receptionist', 1), ('attendant', 2)], default=0, verbose_name='Perfil'),
        ),
    ]
