# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='classification',
            field=models.IntegerField(choices=[(0, 'Não classificado'), (1, 'Atendimento Imediato'), (2, 'Atendimento Ambulatorial'), (3, 'Atendimento Hospitalar'), (4, 'Atendimento Eletivo')], default=0, verbose_name='Classification'),
        ),
    ]
