# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age_range',
        ),
    ]
