# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=50, unique=True, verbose_name='UF')),
                ('city', models.CharField(max_length=50, unique=True, verbose_name='Cidade')),
                ('neighborhood', models.CharField(max_length=100, unique=True, verbose_name='Bairro')),
                ('street', models.CharField(max_length=50, unique=True, verbose_name='Rua')),
                ('block', models.CharField(max_length=50, unique=True, verbose_name='Bloco')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Numero')),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='block',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='city',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='number',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='street',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='attendant',
            name='block',
        ),
        migrations.RemoveField(
            model_name='attendant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='attendant',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='attendant',
            name='number',
        ),
        migrations.RemoveField(
            model_name='attendant',
            name='street',
        ),
        migrations.RemoveField(
            model_name='attendant',
            name='uf',
        ),
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='attendant',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
    ]
