# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age_range',
            field=models.IntegerField(choices=[(1, 'até 28 dias'), (2, '29 dias à 3 meses'), (4, '10 anos ou mais')], default=1, verbose_name='Faixa etária'),
        ),
    ]
