# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_patient_age_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age_range',
            field=models.IntegerField(choices=[(1, 'até 28 dias'), (2, '29 dias à 3 meses')], default=1, verbose_name='Faixa etária'),
        ),
    ]
