# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_receptionist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('guardian', models.CharField(help_text='Informe o nome do responsável', max_length=50, verbose_name='Nome do Responsável')),
                ('birth_date', models.DateTimeField(help_text='Informe a data de Nascimento', verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(default='', help_text='Informe o CPF', max_length=11, unique=True, verbose_name='CPF')),
                ('parents_name', models.CharField(help_text='Informe o nome dos pais', max_length=150, unique=True, verbose_name='Nome dos pais')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
