# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 21:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_myattendant_mypaciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian', models.CharField(help_text='Informe o nome do responsável', max_length=50, verbose_name='Nome do Responsável')),
                ('birth_date', models.DateField(help_text='Informe a data de Nascimento', verbose_name='Data de Nascimento')),
                ('first_name', models.CharField(help_text='Informe o primeiro nome', max_length=50, verbose_name='Nome')),
                ('address', models.CharField(help_text='Informe o endereço', max_length=50, verbose_name='Endereço')),
                ('cpf', models.CharField(help_text='Informe o CPF', max_length=11, verbose_name='CPF')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='Person_ptr',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='person_ptr',
        ),
        migrations.RemoveField(
            model_name='person',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Person_ptr',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='person_ptr',
        ),
        migrations.DeleteModel(
            name='Pacient',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
