# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170916_1813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Pacient',
        ),
    ]
