# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patient_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cep',
            field=models.CharField(default='', help_text='Informe o CEP', max_length=10, verbose_name='CEP'),
        ),
    ]
