# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_queuepatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuepatient',
            name='patient_key',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.Patient'),
            preserve_default=False,
        ),
    ]
