# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_staff_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile',
            field=models.IntegerField(choices=[(1, 'Recepcionista'), (2, 'Atendente')], default=0, verbose_name='Perfil'),
        ),
    ]
