# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171006_1300'),
        ('users', '0002_auto_20171014_1709'),
    ]

    operations = [
    ]
