# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170916_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='block',
            field=models.CharField(max_length=50, unique=True, verbose_name='Conjunto'),
        ),
    ]
