# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171029_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cpf',
            field=models.CharField(blank=True, help_text='Informe o CPF', max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
