# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_queuepatient_patient_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuepatient',
            name='patient_key',
        ),
        migrations.AddField(
            model_name='patient',
            name='isInQueue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='queuePosition',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='QueuePatient',
        ),
    ]
