# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170916_1924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pacient',
            new_name='Patient',
        ),
    ]
