# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171212_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='cep',
            field=models.CharField(default='', max_length=10, verbose_name='CEP'),
        ),
    ]
