# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171013_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='queuePosition',
            field=models.IntegerField(default=0),
        ),
    ]
