# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171031_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age_range',
            field=models.IntegerField(choices=[(1, 'até 28 dias'), (2, '29 dias à 3 meses'), (3, '3 meses à 2 anos'), (4, '2 anos à 10 anos'), (5, 'acima de 10 anos')], default=1, verbose_name='Classification'),
        ),
    ]
