# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171212_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cep',
            field=models.CharField(blank=True, default='', help_text='Informe o CEP', max_length=10, verbose_name='CEP'),
        ),
    ]
