# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171016_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='parents_name',
            field=models.CharField(help_text='Informe o nome dos pais', max_length=150, verbose_name='Nome dos pais'),
        ),
    ]
