# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171108_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
    ]
