# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171111_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age_range',
            field=models.IntegerField(choices=[(0, 'Faixa etária indefinida'), (1, '0 até 28 dias'), (2, '29 dias à 2 meses'), (3, '2 meses à 3 anos'), (4, '3 anos à 10 anos'), (5, 'Acima de 10 anos')], default=0, verbose_name='Classification'),
        ),
    ]
