# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171019_0330'),
        ('users', '0003_merge_20171016_2339'),
    ]

    operations = [
    ]
