# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171114_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='classification',
            field=models.IntegerField(choices=[(0, 'Não classificado'), (1, 'Atendimento Imediato'), (2, 'Atendimento Hospitalar'), (3, 'Atendimento Ambulatorial'), (4, 'Atendimento Eletivo')], default=0, verbose_name='Classification'),
        ),
    ]
