# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20171019_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedPatient',
            fields=[
                ('queuePosition', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='isInQueue',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='queuePosition',
        ),
        migrations.AddField(
            model_name='queuedpatient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Patient'),
        ),
    ]
