# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalState_10yMore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id5', models.CharField(blank=True, max_length=150, verbose_name='ID do Paciente')),
                ('mais_de_72h_febre', models.BooleanField(default=False, verbose_name='Febre a mais de 72 horas')),
                ('menos_de_72h_febre', models.BooleanField(default=False, verbose_name='Febre a menos de 72 horas')),
                ('tontura', models.BooleanField(default=False, verbose_name='Tontura')),
                ('corpo_estranho', models.BooleanField(default=False, verbose_name='Corpo estranho')),
                ('dor_de_dente', models.BooleanField(default=False, verbose_name='Dor de dente')),
                ('disuria', models.BooleanField(default=False, verbose_name='Disúria')),
                ('urina_concentrada', models.BooleanField(default=False, verbose_name='Urina concentrada')),
                ('dispineia', models.BooleanField(default=False, verbose_name='Dispinéia')),
                ('dor_toracica', models.BooleanField(default=False, verbose_name='Dor torácica')),
                ('choque_eletrico', models.BooleanField(default=False, verbose_name='Choque elétrico')),
                ('quase_afogamento', models.BooleanField(default=False, verbose_name='Quase afogamento')),
                ('artralgia', models.BooleanField(default=False, verbose_name='Artralgia')),
                ('ictericia', models.BooleanField(default=False, verbose_name='Icterícia')),
                ('perda_da_consciencia', models.BooleanField(default=False, verbose_name='Perda da conciência')),
                ('palidez', models.BooleanField(default=False, verbose_name='Palidez')),
                ('cianose', models.BooleanField(default=False, verbose_name='Cianose')),
                ('solucos', models.BooleanField(default=False, verbose_name='Soluços')),
                ('prostracao', models.BooleanField(default=False, verbose_name='Prostração')),
                ('febre', models.BooleanField(default=False, verbose_name='Febre')),
                ('vomitos', models.BooleanField(default=False, verbose_name='Vômitos')),
                ('tosse', models.BooleanField(default=False, verbose_name='Tosse')),
                ('coriza', models.BooleanField(default=False, verbose_name='Coriza')),
                ('espirros', models.BooleanField(default=False, verbose_name='Espirros')),
                ('hiperemia_conjuntival', models.BooleanField(default=False, verbose_name='Hiperemia conjuntival')),
                ('obstrucao_nasal', models.BooleanField(default=False, verbose_name='Obstrução nasal')),
                ('convulsao', models.BooleanField(default=False, verbose_name='Convulsão')),
                ('diarreia', models.BooleanField(default=False, verbose_name='Diarreia')),
                ('dificuldade_evacuar', models.BooleanField(default=False, verbose_name='Dificuldade de evacuar')),
                ('cefaleia', models.BooleanField(default=False, verbose_name='Cefaléia')),
                ('manchas_na_pele', models.BooleanField(default=False, verbose_name='Manchas na pele')),
                ('queda', models.BooleanField(default=False, verbose_name='Queda')),
                ('salivacao', models.BooleanField(default=False, verbose_name='Salivação')),
                ('hiporexia', models.BooleanField(default=False, verbose_name='Hiporexia')),
                ('constipacao', models.BooleanField(default=False, verbose_name='Constipação')),
                ('chiado_no_peito', models.BooleanField(default=False, verbose_name='Chiado no peito')),
                ('diminuicao_da_diurese', models.BooleanField(default=False, verbose_name='Diminuição da diurese')),
                ('dor_abdominal', models.BooleanField(default=False, verbose_name='Dor abdominal')),
                ('otalgia', models.BooleanField(default=False, verbose_name='Otalgia')),
                ('epistaxe', models.BooleanField(default=False, verbose_name='Epistaxe')),
                ('otorreia', models.BooleanField(default=False, verbose_name='Otorréia')),
                ('edema', models.BooleanField(default=False, verbose_name='Edema')),
                ('adenomegalias', models.BooleanField(default=False, verbose_name='Adenomegalias')),
                ('dor_articular', models.BooleanField(default=False, verbose_name='Dor articular')),
                ('dificuldade_de_marcha', models.BooleanField(default=False, verbose_name='Dificuldade de marcha')),
                ('sonolencia', models.BooleanField(default=False, verbose_name='Sonolência')),
                ('secrecao_ocular', models.BooleanField(default=False, verbose_name='Secreção ocular')),
                ('dor_muscular', models.BooleanField(default=False, verbose_name='Dor muscular')),
                ('dor_retroorbitaria', models.BooleanField(default=False, verbose_name='Dor Retroorbitária')),
            ],
        ),
    ]
