# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalstate_28d',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Data'),
        ),
    ]
