# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_rating', '0002_clinicalstate_10ymore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalState_3y_10y',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id4', models.CharField(blank=True, max_length=150, verbose_name='ID do Paciente')),
                ('perdada_consciencia', models.BooleanField(default=False, verbose_name='Perda de Consciência')),
                ('febre_maior_72h', models.BooleanField(default=False, verbose_name='Febre Mais de 72 horas')),
                ('febre_menos_72h', models.BooleanField(default=False, verbose_name='Febre Menos de 72 horas')),
                ('odinofagia', models.BooleanField(default=False, verbose_name='Odinofagia')),
                ('fascies_de_dor', models.BooleanField(default=False, verbose_name='Fascies De Dor')),
                ('tontura', models.BooleanField(default=False, verbose_name='Tontura')),
                ('corpo_estranho', models.BooleanField(default=False, verbose_name='Corpo Estranho')),
                ('dor_dentes', models.BooleanField(default=False, verbose_name='Dor de dentes')),
                ('disuria', models.BooleanField(default=False, verbose_name='Disuria')),
                ('urina_concentrada', models.BooleanField(default=False, verbose_name='Urina Concentrada')),
                ('dispineia', models.BooleanField(default=False, verbose_name='Dispinéia')),
                ('dor_toracica', models.BooleanField(default=False, verbose_name='Dor Toracica')),
                ('choque_eletrico', models.BooleanField(default=False, verbose_name='Choque Eletrico')),
                ('quase_afogamento', models.BooleanField(default=False, verbose_name='Quase Afogamento')),
                ('artralgia', models.BooleanField(default=False, verbose_name='Artralgia')),
                ('ictericia', models.BooleanField(default=False, verbose_name='Icterícia')),
                ('perda_consciencia', models.BooleanField(default=False, verbose_name='Perda de consciencia')),
                ('palidez', models.BooleanField(default=False, verbose_name='Palidez')),
                ('cianose', models.BooleanField(default=False, verbose_name='Cianose')),
                ('solucos', models.BooleanField(default=False, verbose_name='Soluços')),
                ('prostracao', models.BooleanField(default=False, verbose_name='Prostração')),
                ('febre', models.BooleanField(default=False, verbose_name='Febre')),
                ('vomitos', models.BooleanField(default=False, verbose_name='Vomitos')),
                ('tosse', models.BooleanField(default=False, verbose_name='Tosse')),
                ('coriza', models.BooleanField(default=False, verbose_name='Coriza')),
                ('espirros', models.BooleanField(default=False, verbose_name='Espirros')),
                ('hiperemia_conjuntival', models.BooleanField(default=False, verbose_name='Hiperemia Conjuntival')),
                ('secrecao_ocular', models.BooleanField(default=False, verbose_name='Secrecao Ocular')),
                ('obstrucao_nasal', models.BooleanField(default=False, verbose_name='Obstrução Nasal')),
                ('convulsao', models.BooleanField(default=False, verbose_name='Convulsão')),
                ('diarreia', models.BooleanField(default=False, verbose_name='Diarreia')),
                ('manchas_na_pele', models.BooleanField(default=False, verbose_name='Manchas na pele')),
                ('queda', models.BooleanField(default=False, verbose_name='Queda')),
                ('hiporexia', models.BooleanField(default=False, verbose_name='Hiporexia')),
                ('salivacao', models.BooleanField(default=False, verbose_name='Salivacao')),
                ('constipacao', models.BooleanField(default=False, verbose_name='Constipação')),
                ('chiado_no_peito', models.BooleanField(default=False, verbose_name='Chiado no Peito')),
                ('diminuicao_da_diurese', models.BooleanField(default=False, verbose_name='Diminuição da Diurese')),
                ('dor_abdominal', models.BooleanField(default=False, verbose_name='Dor Abdominal')),
                ('otalgia', models.BooleanField(default=False, verbose_name='Otalgia')),
                ('epistaxe', models.BooleanField(default=False, verbose_name='Epistaxe')),
                ('otorreia', models.BooleanField(default=False, verbose_name='Otorreia')),
                ('edema', models.BooleanField(default=False, verbose_name='Edema')),
                ('adenomegalias', models.BooleanField(default=False, verbose_name='Adenomegalias')),
                ('dor_articular', models.BooleanField(default=False, verbose_name='Dor Articular')),
                ('dificulade_de_marchar', models.BooleanField(default=False, verbose_name='Dificuldade Marchar')),
                ('sonolencia', models.BooleanField(default=False, verbose_name='Sonolência')),
                ('dor_muscular', models.BooleanField(default=False, verbose_name='Dor Muscular')),
                ('dor_retroorbitaria', models.BooleanField(default=False, verbose_name='Dor Retroorbitária')),
            ],
        ),
    ]
