# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_rating', '0002_auto_20171128_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalstate_10ymore',
            name='classifier_id',
        ),
        migrations.RemoveField(
            model_name='clinicalstate_28d',
            name='classifier_id',
        ),
        migrations.RemoveField(
            model_name='clinicalstate_29d_2m',
            name='classifier_id',
        ),
        migrations.RemoveField(
            model_name='clinicalstate_2m_3y',
            name='classifier_id',
        ),
        migrations.RemoveField(
            model_name='clinicalstate_3y_10y',
            name='classifier_id',
        ),
    ]
