# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_rating', '0003_clinicalstate_3y_10y'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicalstate_3y_10y',
            old_name='patient_id4',
            new_name='patient_id',
        ),
    ]
